install resources from shadow-repository

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,7 @@
 #!/bin/bash
 thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 cd $thisdir
+res=0
 #
 # Tarballs and their url's
 #
@@ -12,6 +13,7 @@ ims_lib_ball="lib.tar.gz"
 #ims_lib_urldir="http://www.comp.nus.edu.sg/~nlp/sw"
 ims_models_ball="models.tar.gz"
 alt_ims_models_ball="20181023_models.tar.gz"
+ims_resources_ball=ims_resources.tgz
 wordnet_version="1.7.1"
 wordnet_urldir="http://wordnetcode.princeton.edu/${wordnet_version}"
 wordnet_ball="WordNet-${wordnet_version}.tar.gz"
@@ -21,61 +23,46 @@ wordnet_ball="WordNet-${wordnet_version}.tar.gz"
 
 function get_and_unpack_ball () {
     url_dir=$1
-    second_url_dir=$2
-    ball=$3
+    ball=$2
     wget ${url_dir}/${ball}
     result=$?
     if
        [ $result -gt 0 ]
     then
-       wget ${second_url_dir}/${ball}
-       result=$?
+	echo "Cannot download $ball" >&2
+	exit 4 
     fi
+    tar -xzf ${ball}
+    result=$?
     if
-       [ $result == 0 ]
+	[ $result == 0 ]
     then
-	tar -xzf ${ball}
 	rm ${ball}
     else
-	echo "Cannot download $ball"
+	echo "Cannot unpack $ball" >&2
+	exit 4
     fi
 }
 
 
 # For the main package
-
-get_and_unpack_ball ${ims_urldir} ${ims_second_urldir} ${ims_ball}
-mv ims_0.9.2.1 ims
+get_and_unpack_ball ${ims_second_urldir} ${ims_ball}
+mv ${ims_ball} ims
 
 # For the library
 cd ${thisdir}/ims
 chmod +x testPlain.bash
-get_and_unpack_ball ${ims_urldir} ${ims_second_urldir} ${ims_lib_ball}
+get_and_unpack_ball ${ims_second_urldir} ${ims_lib_ball}
 
 # For the models
-# get_and_unpack_ball ${ims_urldir} ${ims_second_urldir} ${ims_models_ball}
-wget ${ims_second_urldir}/${alt_ims_models_ball}
-result=$?
-if
-   [ $result -gt 0 ]
-then
-    echo "Cannot download from ${ims_second_url_dir}/${alt_ims_models_ball}"
-else
-    tar -xzf ${alt_ims_models_ball}
-    rm ${alt_ims_models_ball}
-fi
-
-
+get_and_unpack_ball ${ims_second_urldir} ${alt_ims_models_ball}
 
 cd ${thisdir}
 
 # TODO: find solution for path_to_ims.py.
-
 # Temporary solution while url http://nlp.lsi.upc.edu/tools/download-map.php is broken.
 
-wget http://kyoto.let.vu.nl/nlpp_repo/it_makes_sense_WSD/ims_resources.tgz
-tar -xzf ims_resources.tgz
-rm ims_resources.tgz
+get_and_unpack_ball ${ims_second_urldir} ${ims_resources_ball}
 
 #mkdir resources
 #cd resources
